# Specify system and language
language: generic

# Build only on main
branches:
  only:
    - main

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - graphviz

# Generate documentation
script:
  make docs

# Deploy docs to GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/doxygen/html
  on:
    branch: main
